### ISSUE TITLE
Links not working in footer

### ISSUE THREAD

**Issue by Rajm1505** [xoxzo/xoxzo.github.io#4]
Links like 'Hiring' and 'Twitter' are not working in the footer
Also, the Copyright statement is outdated.

![image](https://github.com/xoxzo/xoxzo.github.io/assets/95242392/e22e5abd-cd8a-4aca-8a07-a5cff92ec99a)

I would love to contribute to the issue.

**Comment by josefmonje** [comment]
Thank you for your submission, we appreciate you looking at it.  May I ask, how did you find us and our repo? We don't use it at the moment so I'd have to close the issue but I appreciate you bringing our attention to it.

**Comment by Rajm1505** [comment]
Hello Josef,

I am Raj, Few months ago I came across Xoxzo hiring on LinkedIn and applied
to it. Unfortunately, I didn't get the interview. I like what Xoxzo does,
In fact, I have a project for a "Bulk emailing and retrieval system" and
have a keen interest in the same. So, anyways I wanted to contribute to
what Xoxzo is doing, It would be great if you can point to me a repository
where contributions are welcomed or required.
Looking forward to hearing from you.

Thank you
Raj Mandaviya
